artifact_uri: file:D:/HocPython/deep learning/Computer Vision/gun detection/runs/mlflow/623991071833487009/639df2275a574b90ab50945e9e9dbbe7/artifacts
end_time: 1766346644741
entry_point_name: ''
experiment_id: '623991071833487009'
lifecycle_stage: active
run_id: 639df2275a574b90ab50945e9e9dbbe7
run_name: gun_detector
source_name: ''
source_type: 4
source_version: ''
start_time: 1766345287171
status: 3
tags: []
user_id: PC
