artifact_uri: file:D:/HocPython/deep learning/Computer Vision/gun detection/runs/mlflow/623991071833487009/4fbb3fcc4bd94d3f81d0c164a3aee3b4/artifacts
end_time: 1766340635316
entry_point_name: ''
experiment_id: '623991071833487009'
lifecycle_stage: active
run_id: 4fbb3fcc4bd94d3f81d0c164a3aee3b4
run_name: gun_detector9
source_name: ''
source_type: 4
source_version: ''
start_time: 1766340586028
status: 3
tags: []
user_id: PC
