artifact_uri: file:D:/HocPython/deep learning/Computer Vision/gun detection/runs/mlflow/623991071833487009/48a437c0f32d49ba9d1f9b77130fbf4b/artifacts
end_time: 1766404858911
entry_point_name: ''
experiment_id: '623991071833487009'
lifecycle_stage: active
run_id: 48a437c0f32d49ba9d1f9b77130fbf4b
run_name: gun_detector_tb
source_name: ''
source_type: 4
source_version: ''
start_time: 1766401191326
status: 3
tags: []
user_id: PC
