artifact_location: file:D:/HocPython/deep learning/Computer Vision/gun detection/runs/mlflow/0
creation_time: 1766340585897
experiment_id: '0'
last_update_time: 1766340585897
lifecycle_stage: active
name: Default
