artifact_uri: file:D:/HocPython/deep learning/Computer Vision/gun detection/runs/mlflow/623991071833487009/21ffd518097d4e0ea059ec10184e5ade/artifacts
end_time: 1766401098085
entry_point_name: ''
experiment_id: '623991071833487009'
lifecycle_stage: active
run_id: 21ffd518097d4e0ea059ec10184e5ade
run_name: gun_detector_tb
source_name: ''
source_type: 4
source_version: ''
start_time: 1766400877151
status: 3
tags: []
user_id: PC
